x-healthcheck:
  healthcheck:
    &healthcheck-common
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  mc:
    image: minio/mc:latest
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin --api S3v4) do echo '...waiting...' && sleep 1; done; 
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master
    depends_on:
      - minio
    healthcheck:
      <<: *healthcheck-common
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
    hostname: spark-master
    image: spark-prod
    ports:
      - "8198:8080"
    restart: unless-stopped
    volumes:
      - ./spark/spark-logs:/opt/spark/logs
      - ./spark/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
      - ./data:/home/spark/work/data
  spark-worker-1:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
    healthcheck:
      <<: *healthcheck-common
      test: ['CMD', 'curl', '-f', 'http://localhost:8081']
    hostname: spark-worker
    image: spark-prod
    ports:
      - "8181:8081"
    restart: unless-stopped
    volumes:
      - ./spark/spark-logs:/opt/spark/logs
      - ./spark/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
      - ./data:/home/spark/work/data
  spark-worker-2:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
    healthcheck:
      <<: *healthcheck-common
      test: ['CMD', 'curl', '-f', 'http://localhost:8081']
    hostname: spark-worker
    image: spark-prod
    ports:
      - "8182:8081"
    restart: unless-stopped
    volumes:
      - ./spark/spark-logs:/opt/spark/logs
      - ./spark/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
      - ./data:/home/spark/work/data
  spark-history:
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: spark-prod
    container_name: spark-history
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
      --properties-file /opt/spark/conf/spark-defaults.conf
    environment:
    - SPARK_EVENTLOG_DIR=file:/opt/spark/events
    - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/opt/spark/events
    ports:
      - "18189:18080"
    depends_on:
      - spark-master
    volumes:
      - ./spark/spark-logs:/opt/spark/logs
      - ./spark/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
    restart: unless-stopped

  jupyter:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8994:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    depends_on:
      - spark-master
    volumes:
      - ./notebooks:/home/spark/work
      - ./data:/home/spark/work/data
      - ./spark/spark-logs:/opt/spark/logs
      - ./spark/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
    restart: always # In case of service/container crash, the container will restart.


  postgres-metastore:
    image: postgres:17
    container_name: postgres-metastore
    hostname: postgres-metastore
    ports:
      - 5467:5432
    environment:
      POSTGRES_USER: ${HIVE_METASTORE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HIVE_METASTORE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HIVE_METASTORE_POSTGRES_DB}
    volumes:
      - ./hive/postgresql/data:/var/lib/postgresql/data
      - ./hive/scripts:/docker-entrypoint-initdb.d
      - ./hive/scripts/init_hive.sql:/docker-entrypoint-initdb.d/init_hive.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      retries: 5

  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    image: 'starburstdata/hive:3.1.3-e.15'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: ${HIVE_METASTORE_JDBC_URL}
      HIVE_METASTORE_USER: ${HIVE_METASTORE_USER}
      HIVE_METASTORE_PASSWORD: ${HIVE_METASTORE_PASSWORD}
      HIVE_METASTORE_WAREHOUSE_DIR: ${HIVE_METASTORE_WAREHOUSE_DIR}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
        postgres-metastore:
          condition: service_healthy

  trino-coordinator:
    image: trinodb/trino:400
    hostname: trino-coordinator
    container_name: trino-coordinator
    ports:
      # Trino UI and coordinator service exposed on port 8080. You can change the host-side port if needed.
      - '8087:8080'
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/trino/data
    environment:
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}

  postgres-metabase:
    image: postgres:17
    container_name: postgres-metabase
    hostname: postgres
    environment:
      POSTGRES_USER: ${METABASE_POSTGRES_USER}
      POSTGRES_DB: ${METABASE_POSTGRES_DB}
      POSTGRES_PASSWORD: ${METABASE_POSTGRES_PASSWORD}
    ports:
      - 5457:5432
    volumes:
      - ./metabase/postgresql/data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.56.x
    container_name: metabase
    hostname: metabase
    volumes:
      - /metabase/dev/urandom:/dev/random:ro
    ports:
      - 3077:3000
    environment:
      MB_DB_TYPE: ${METABASE_DB_TYPE}
      MB_DB_DBNAME: ${METABASE_DB_DBNAME}
      MB_DB_PORT: ${METABASE_DB_PORT}
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      MB_DB_HOST: ${METABASE_DB_HOST}
    depends_on:
      - postgres-metabase
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5